### ISSUE TITLE
On Ubuntu 16.04 doesn't work

### ISSUE THREAD

**Issue by mrlioncub** [node-ci/nci-ansible-ui#7]
On Ubuntu 16.04 doesn't work:
npm and build-essential installed!
```
# git clone https://github.com/node-ci/nci-ansible-ui-quick-setup && cd nci-ansible-ui-quick-setup && npm install
Клонирование в «nci-ansible-ui-quick-setup»…
remote: Counting objects: 30, done.
remote: Total 30 (delta 0), reused 0 (delta 0), pack-reused 30
Распаковка объектов: 100% (30/30), готово.
Проверка соединения… готово.
loadDep:uuid → resolveWit ▐ ╢████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN prefer global node-ninja@1.0.2 should be installed with -g
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> leveldown@1.5.0 install /tmp/nci-ansible-ui-quick-setup/node_modules/leveldown
> prebuild --install

/usr/bin/env: «node»: Нет такого файла или каталога
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN optional Skipping failed optional dependency /nci-projects-reloader/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm ERR! Linux 4.4.0-101-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! leveldown@1.5.0 install: `prebuild --install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the leveldown@1.5.0 install script 'prebuild --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/nci-ansible-ui-quick-setup/npm-debug.log
```
[npm-debug.log](https://github.com/node-ci/nci-ansible-ui/files/1513516/npm-debug.log)

**Comment by okv** [comment]
> /usr/bin/env: «node»: Нет такого файла или каталога

Seems like you have some trouble with your node.js installation.

**Comment by okv** [comment]
I've just tried

```sh
git clone https://github.com/node-ci/nci-ansible-ui-quick-setup && cd nci-ansible-ui-quick-setup && npm install
```

with nodejs and npm versions from your npm-debug.log (node@v4.2.6 npm@3.5.2) on Ubuntu 16.04.3 LTS - everything looks good.

**Comment by mrlioncub** [comment]
Sorry, but system new (clean)!
1. apt install npm nodejs-legacy
2. git clone https://github.com/node-ci/nci-ansible-ui-quick-setup && cd nci-ansible-ui-quick-setup && npm install
```
# npm install
loadDep:uuid → addNameRan ▀ ╢████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN prefer global node-ninja@1.0.2 should be installed with -g
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> leveldown@1.5.0 install /tmp/nci-ansible-ui-quick-setup/node_modules/leveldown
> prebuild --install

prebuild WARN install socket hang up
prebuild WARN install got an error, rolling back install
prebuild ERR! configure error 
prebuild ERR! stack Error: tunneling socket could not be established, cause=Parse Error
prebuild ERR! stack     at ClientRequest.onError (/tmp/nci-ansible-ui-quick-setup/node_modules/tunnel-agent/index.js:177:17)
prebuild ERR! stack     at ClientRequest.g (events.js:260:16)
prebuild ERR! stack     at emitOne (events.js:77:13)
prebuild ERR! stack     at ClientRequest.emit (events.js:169:7)
prebuild ERR! stack     at Socket.socketOnData (_http_client.js:309:9)
prebuild ERR! stack     at emitOne (events.js:77:13)
prebuild ERR! stack     at Socket.emit (events.js:169:7)
prebuild ERR! stack     at readableAddChunk (_stream_readable.js:146:16)
prebuild ERR! stack     at Socket.Readable.push (_stream_readable.js:110:10)
prebuild ERR! stack     at TCP.onread (net.js:523:20)
prebuild ERR! not ok 
prebuild ERR! build Error: tunneling socket could not be established, cause=Parse Error
prebuild ERR! build     at ClientRequest.onError (/tmp/nci-ansible-ui-quick-setup/node_modules/tunnel-agent/index.js:177:17)
prebuild ERR! build     at ClientRequest.g (events.js:260:16)
prebuild ERR! build     at emitOne (events.js:77:13)
prebuild ERR! build     at ClientRequest.emit (events.js:169:7)
prebuild ERR! build     at Socket.socketOnData (_http_client.js:309:9)
prebuild ERR! build     at emitOne (events.js:77:13)
prebuild ERR! build     at Socket.emit (events.js:169:7)
prebuild ERR! build     at readableAddChunk (_stream_readable.js:146:16)
prebuild ERR! build     at Socket.Readable.push (_stream_readable.js:110:10)
prebuild ERR! build     at TCP.onread (net.js:523:20)
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN optional Skipping failed optional dependency /nci-projects-reloader/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm ERR! Linux 4.4.0-101-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.5.0 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the leveldown@1.5.0 install script 'prebuild --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/nci-ansible-ui-quick-setup/npm-debug.log
```
[npm-debug.log](https://github.com/node-ci/nci-ansible-ui/files/1520501/npm-debug.log)
What other requirements?

**Comment by okv** [comment]
All known requirements are listed.

I tried that in docker:

```sh
docker run -it --rm ubuntu:16.04 bash
```

and inside container:

```sh
apt-get update
apt-get install -V nodejs-legacy npm git
cd /tmp/
git clone https://github.com/node-ci/nci-ansible-ui-quick-setup && cd nci-ansible-ui-quick-setup && npm install
node_modules/.bin/nci
```

Everything looks good.

**Comment by mrlioncub** [comment]
I would like to run without a docker.

**Comment by okv** [comment]
I've only used docker to demonstrate that it will correctly work on new/clean system.

**Comment by okv** [comment]
Looks like specific local problem, closing it...
