### ISSUE TITLE
Add --extra-vars arg ansible

### ISSUE THREAD

**Issue by RomyxBaps** [node-ci/nci-ansible-ui#9]
Hi,

First of all, thank you for your great work ! It a very cool application for ansible, just what I need.
I have a request/question, I want to add after the "Limit" form an ExtraVard form.

I tried already to add but I don't know where to add this feature.
Where to add the variable and the form in the js/script/html ? 

Thanks

**Comment by okv** [comment]
Hi.

It's nice to hear that this ui is useful for someone else.

In order to add another parameter you should do that on both sides (client and server). I'll try to take a look at that and tell you more details. Currently don't have enough time to do so.

**Comment by RomyxBaps** [comment]
Hi,

Thank you for your quick response !

I don't know very well NodeJS so it's a little difficult for me to change some parameter.
I tried and I arrived at the point where extravars wasn't define.

**Comment by RomyxBaps** [comment]
Hi,

For output, I have this, I miss something but don't know what it is : 
``[Tue, 10 Jul 2018 13:49:13 GMT] [projects resource] Run the project: "some_project" with params: {"playbook":{"name":"Ping","inventoryNames":["sample"]}}
[Tue, 10 Jul 2018 13:49:13 GMT] [distributor] Error during run:  ReferenceError: extravars is not defined
    at {home_site}/docroot/node_modules/nci-ansible-ui/resources/projects.js:66:11
    at Function._.map._.collect ({home_site}/docroot/node_modules/underscore/underscore.js:172:24)
    at _.(anonymous function) [as map] ({home_site}/docroot/node_modules/underscore/underscore.js:1496:34)
    at makeProject ({home_site}/docroot/node_modules/nci-ansible-ui/resources/projects.js:55:38)
    at Distributor.distributor._makeProject ({home_site}/docroot/node_modules/nci-ansible-ui/resources/projects.js:102:16)
    at Group.<anonymous> ({home_site}/docroot/node_modules/nci/lib/distributor.js:549:19)
    at Group.<anonymous> ({home_site}/docroot/node_modules/twostep/lib/twoStep.js:171:15)
    at next ({home_site}/docroot/node_modules/twostep/lib/twoStep.js:159:9)
    at iterateSteps ({home_site}/docroot/node_modules/twostep/lib/twoStep.js:164:7)
    at `{home_site}/docroot/node_modules/twostep/lib/twoStep.js:129:3``

``[Tue, 10 Jul 2018 13:50:54 GMT] [projects resource] Run the project: "some_project" with params: {"playbook":{"name":"Ping","inventoryNames":["sample"],"limit":"\"urlfilter=www.test.fr\""}}
[Tue, 10 Jul 2018 13:50:54 GMT] [distributor] Error during run:  ReferenceError: extravars is not defined
    at {home_site}/docroot/node_modules/nci-ansible-ui/resources/projects.js:66:11
    at Function._.map._.collect ({home_site}/docroot/node_modules/underscore/underscore.js:172:24)
    at _.(anonymous function) [as map] ({home_site}/docroot/node_modules/underscore/underscore.js:1496:34)
    at makeProject ({home_site}/docroot/node_modules/nci-ansible-ui/resources/projects.js:55:38)
    at Distributor.distributor._makeProject ({home_site}/docroot/node_modules/nci-ansible-ui/resources/projects.js:102:16)
    at Group.<anonymous> ({home_site}/docroot/node_modules/nci/lib/distributor.js:549:19)
    at Group.<anonymous> ({home_site}/docroot/node_modules/twostep/lib/twoStep.js:171:15)
    at next ({home_site}/docroot/node_modules/twostep/lib/twoStep.js:159:9)
    at iterateSteps ({home_site}/docroot/node_modules/twostep/lib/twoStep.js:164:7)
    at {home_site}/docroot/node_modules/twostep/lib/twoStep.js:129:3``

**Comment by RomyxBaps** [comment]
Hi,

Do you have some news ?

**Comment by okv** [comment]
Hi.

Didn't look at that yet.
Unfortunately can’t currently say when I'll do that.

**Comment by RomyxBaps** [comment]
Hi, did you have a look on the extra-vars during the summer ? 
I'm gonna retry to add on my side the extra-vars too.

**Comment by okv** [comment]
Still nothing to say about that, sorry.

**Comment by okv** [comment]
I'm working on it #10
It seems to work, just want to check it before merge.
Hope to deal with it at begin of the week.

**Comment by RomyxBaps** [comment]
Thank you a lot for your work ! :)

**Comment by okv** [comment]
Merged, published to npm as nci-ansible-ui@1.1.0
